spring:
  datasource:
    username: postgres
    password: 2001
    url: jdbc:postgresql://localhost:5432/travel_log
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

api:
  info:
    title: Travel Log
    description: Software that controls the use of company cars
    version: 1.0
    terms-of-service: https://unicorn.pdp.uz
    contact-name: pdp.uz
    contact-email: mutalov7777@gmail.com
    contact-url: https://pdp.uz
    license-name: Apache 2.0
    license-url: https://www.apache.org/licenses/LICENSE-2.0.html

service:
  prop:
    protocol: http
    ip: localhost
    port: 8080
    url: boom.uz

springdoc:
  swagger-ui:
    path: swagger-ui
  api-docs:
    path: /api-docs
